server:
  port: 8089
  servlet:
    context-path: ""
  tomcat:
    max-threads: 1000
    min-spare-threads: 50
  connection-timeout: 5000
spring:
  #配置solr全文搜索引擎
  data:
    solr:
      host: http://127.0.0.1:8983/solr
  #添加默认环境
  profiles:
    active: dev
  mvc:
    view:
      prefix: /
      suffix: .jsp
  #添加数据库
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: HuangHao2012
    driver-class-name: com.mysql.cj.jdbc.Driver
    #连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    dbcp2:
      initial-size: 10
      min-idle: 5
      # 配置获取连接等待超时的时间
      max-wait-millis: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 测试连接是否有效的sql
      validationQuery: select 'x'
      # 建议配置为true，不影响性能，并且保证安全性
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      testWhileIdle: true
      # 申请连接时执行validationQuery检测连接是否有效
      testOnBorrow: false
      # 归还连接时执行validationQuery检测连接是否有效
      testOnReturn: false
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
      maxPoolPreparedStatementPerConnectionSize: 50
      # 属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：
      # 监控统计用的filter:stat
      # 日志用的filter:log4j
      # 防御sql注入的filter:wall
      filters: stat
      cachePrepStmts: true#开启二级缓存
    tomcat:
      max-active: 100
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379 
    password: 
    jedis:
      pool:
      # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    # 连接超时时间（毫秒）
    timeout: 2000   